import subprocess
import sys
import shlex


def run(cmd):
    print(f">>> {cmd}", flush=True)
    # shell=False is safer; use a list for args
    proc = subprocess.run(shlex.split(cmd), check=True)
    return proc.returncode

# clinical_cols = ['AgeStartRT', 'Volume_cm3_TotalGTV', 'FractionDose', 'FractionDailyFrequency', 'Sex', 'Nstage', 'Mstage', 'SmokingStatus', 'CellType', 'PulmonaryComorbidity', 'CardiacComorbidity', 'Diabetes', 'AdjuvantImmunotherapy', 'ChemoSequence']
# categorical_cols = ['Sex', 'Nstage', 'Mstage', 'SmokingStatus', 'CellType', 'PulmonaryComorbidity', 'CardiacComorbidity', 'Diabetes', 'AdjuvantImmunotherapy', 'ChemoSequence']

clinical_cols = []
categorical_cols = []

log_folder = "/home/ann/Code/OutcomePrediction/Logs/Clinical/SurvivalPrediction/SimpleCNN/CoxLoss/AdamRes"

# steps = [
#     f'python /home/ann/Code/OutcomePrediction/Classification.py --set RUN.cv_fold=0 RUN.max_epochs=700 RUN.train_fraction=0.25 MODEL.learning_rate=2.5e-3 MODEL.dropout_prob=0.5 DATA.model_name="DSize0.25" MODEL.optimizer="Adam" MODEL.opt_params=dict() DATA.clinical_cols="{clinical_cols}" DATA.categorical_cols="{categorical_cols}" DATA.patient_ids_file_path="SubjectList.csv" RECORDS.records=0 DATA.log_folder={log_folder}',
#     f'python /home/ann/Code/OutcomePrediction/Classification.py --set RUN.cv_fold=1 RUN.max_epochs=700 RUN.train_fraction=0.25 MODEL.learning_rate=2.5e-3 MODEL.dropout_prob=0.5 DATA.model_name="DSize0.25" MODEL.optimizer="Adam" MODEL.opt_params=dict() DATA.clinical_cols="{clinical_cols}" DATA.categorical_cols="{categorical_cols}" DATA.patient_ids_file_path="SubjectList.csv" RECORDS.records=0 DATA.log_folder={log_folder}',
#     f'python /home/ann/Code/OutcomePrediction/Classification.py --set RUN.cv_fold=2 RUN.max_epochs=700 RUN.train_fraction=0.25 MODEL.learning_rate=2.5e-3 MODEL.dropout_prob=0.5 DATA.model_name="DSize0.25" MODEL.optimizer="Adam" MODEL.opt_params=dict() DATA.clinical_cols="{clinical_cols}" DATA.categorical_cols="{categorical_cols}" DATA.patient_ids_file_path="SubjectList.csv" RECORDS.records=0 DATA.log_folder={log_folder}',
#     f'python /home/ann/Code/OutcomePrediction/Classification.py --set RUN.cv_fold=3 RUN.max_epochs=700 RUN.train_fraction=0.25 MODEL.learning_rate=2.5e-3 MODEL.dropout_prob=0.5 DATA.model_name="DSize0.25" MODEL.optimizer="Adam" MODEL.opt_params=dict() DATA.clinical_cols="{clinical_cols}" DATA.categorical_cols="{categorical_cols}" DATA.patient_ids_file_path="SubjectList.csv" RECORDS.records=0 DATA.log_folder={log_folder}',
#     f'python /home/ann/Code/OutcomePrediction/Classification.py --set RUN.cv_fold=4 RUN.max_epochs=700 RUN.train_fraction=0.25 MODEL.learning_rate=2.5e-3 MODEL.dropout_prob=0.5 DATA.model_name="DSize0.25" MODEL.optimizer="Adam" MODEL.opt_params=dict() DATA.clinical_cols="{clinical_cols}" DATA.categorical_cols="{categorical_cols}" DATA.patient_ids_file_path="SubjectList.csv" RECORDS.records=0 DATA.log_folder={log_folder}',
#     f'python /home/ann/Code/OutcomePrediction/Classification.py --set RUN.cv_fold=5 RUN.max_epochs=700 RUN.train_fraction=0.25 MODEL.learning_rate=2.5e-3 MODEL.dropout_prob=0.5 DATA.model_name="DSize0.25" MODEL.optimizer="Adam" MODEL.opt_params=dict() DATA.clinical_cols="{clinical_cols}" DATA.categorical_cols="{categorical_cols}" DATA.patient_ids_file_path="SubjectList.csv" RECORDS.records=0 DATA.log_folder={log_folder}',
#     f'python /home/ann/Code/OutcomePrediction/Classification.py --set RUN.cv_fold=6 RUN.max_epochs=700 RUN.train_fraction=0.25 MODEL.learning_rate=2.5e-3 MODEL.dropout_prob=0.5 DATA.model_name="DSize0.25" MODEL.optimizer="Adam" MODEL.opt_params=dict() DATA.clinical_cols="{clinical_cols}" DATA.categorical_cols="{categorical_cols}" DATA.patient_ids_file_path="SubjectList.csv" RECORDS.records=0 DATA.log_folder={log_folder}',
#     f'python /home/ann/Code/OutcomePrediction/Classification.py --set RUN.cv_fold=7 RUN.max_epochs=700 RUN.train_fraction=0.25 MODEL.learning_rate=2.5e-3 MODEL.dropout_prob=0.5 DATA.model_name="DSize0.25" MODEL.optimizer="Adam" MODEL.opt_params=dict() DATA.clinical_cols="{clinical_cols}" DATA.categorical_cols="{categorical_cols}" DATA.patient_ids_file_path="SubjectList.csv" RECORDS.records=0 DATA.log_folder={log_folder}',
#     f'python /home/ann/Code/OutcomePrediction/Classification.py --set RUN.cv_fold=8 RUN.max_epochs=700 RUN.train_fraction=0.25 MODEL.learning_rate=2.5e-3 MODEL.dropout_prob=0.5 DATA.model_name="DSize0.25" MODEL.optimizer="Adam" MODEL.opt_params=dict() DATA.clinical_cols="{clinical_cols}" DATA.categorical_cols="{categorical_cols}" DATA.patient_ids_file_path="SubjectList.csv" RECORDS.records=0 DATA.log_folder={log_folder}',
#     f'python /home/ann/Code/OutcomePrediction/Classification.py --set RUN.cv_fold=9 RUN.max_epochs=700 RUN.train_fraction=0.25 MODEL.learning_rate=2.5e-3 MODEL.dropout_prob=0.5 DATA.model_name="DSize0.25" MODEL.optimizer="Adam" MODEL.opt_params=dict() DATA.clinical_cols="{clinical_cols}" DATA.categorical_cols="{categorical_cols}" DATA.patient_ids_file_path="SubjectList.csv" RECORDS.records=0 DATA.log_folder={log_folder}',
#     f'python /home/ann/Code/OutcomePrediction/Classification.py --set RUN.cv_fold=0 RUN.max_epochs=700 RUN.train_fraction=0.75 MODEL.learning_rate=2.5e-3 MODEL.dropout_prob=0.5 DATA.model_name="DSize0.75" MODEL.optimizer="Adam" MODEL.opt_params=dict() DATA.clinical_cols="{clinical_cols}" DATA.categorical_cols="{categorical_cols}" DATA.patient_ids_file_path="SubjectList.csv" RECORDS.records=0 DATA.log_folder={log_folder}',
#     f'python /home/ann/Code/OutcomePrediction/Classification.py --set RUN.cv_fold=1 RUN.max_epochs=700 RUN.train_fraction=0.75 MODEL.learning_rate=2.5e-3 MODEL.dropout_prob=0.5 DATA.model_name="DSize0.75" MODEL.optimizer="Adam" MODEL.opt_params=dict() DATA.clinical_cols="{clinical_cols}" DATA.categorical_cols="{categorical_cols}" DATA.patient_ids_file_path="SubjectList.csv" RECORDS.records=0 DATA.log_folder={log_folder}',
#     f'python /home/ann/Code/OutcomePrediction/Classification.py --set RUN.cv_fold=2 RUN.max_epochs=700 RUN.train_fraction=0.75 MODEL.learning_rate=2.5e-3 MODEL.dropout_prob=0.5 DATA.model_name="DSize0.75" MODEL.optimizer="Adam" MODEL.opt_params=dict() DATA.clinical_cols="{clinical_cols}" DATA.categorical_cols="{categorical_cols}" DATA.patient_ids_file_path="SubjectList.csv" RECORDS.records=0 DATA.log_folder={log_folder}',
#     f'python /home/ann/Code/OutcomePrediction/Classification.py --set RUN.cv_fold=3 RUN.max_epochs=700 RUN.train_fraction=0.75 MODEL.learning_rate=2.5e-3 MODEL.dropout_prob=0.5 DATA.model_name="DSize0.75" MODEL.optimizer="Adam" MODEL.opt_params=dict() DATA.clinical_cols="{clinical_cols}" DATA.categorical_cols="{categorical_cols}" DATA.patient_ids_file_path="SubjectList.csv" RECORDS.records=0 DATA.log_folder={log_folder}',
#     f'python /home/ann/Code/OutcomePrediction/Classification.py --set RUN.cv_fold=4 RUN.max_epochs=700 RUN.train_fraction=0.75 MODEL.learning_rate=2.5e-3 MODEL.dropout_prob=0.5 DATA.model_name="DSize0.75" MODEL.optimizer="Adam" MODEL.opt_params=dict() DATA.clinical_cols="{clinical_cols}" DATA.categorical_cols="{categorical_cols}" DATA.patient_ids_file_path="SubjectList.csv" RECORDS.records=0 DATA.log_folder={log_folder}',
#     f'python /home/ann/Code/OutcomePrediction/Classification.py --set RUN.cv_fold=5 RUN.max_epochs=700 RUN.train_fraction=0.75 MODEL.learning_rate=2.5e-3 MODEL.dropout_prob=0.5 DATA.model_name="DSize0.75" MODEL.optimizer="Adam" MODEL.opt_params=dict() DATA.clinical_cols="{clinical_cols}" DATA.categorical_cols="{categorical_cols}" DATA.patient_ids_file_path="SubjectList.csv" RECORDS.records=0 DATA.log_folder={log_folder}',
#     f'python /home/ann/Code/OutcomePrediction/Classification.py --set RUN.cv_fold=6 RUN.max_epochs=700 RUN.train_fraction=0.75 MODEL.learning_rate=2.5e-3 MODEL.dropout_prob=0.5 DATA.model_name="DSize0.75" MODEL.optimizer="Adam" MODEL.opt_params=dict() DATA.clinical_cols="{clinical_cols}" DATA.categorical_cols="{categorical_cols}" DATA.patient_ids_file_path="SubjectList.csv" RECORDS.records=0 DATA.log_folder={log_folder}',
#     f'python /home/ann/Code/OutcomePrediction/Classification.py --set RUN.cv_fold=7 RUN.max_epochs=700 RUN.train_fraction=0.75 MODEL.learning_rate=2.5e-3 MODEL.dropout_prob=0.5 DATA.model_name="DSize0.75" MODEL.optimizer="Adam" MODEL.opt_params=dict() DATA.clinical_cols="{clinical_cols}" DATA.categorical_cols="{categorical_cols}" DATA.patient_ids_file_path="SubjectList.csv" RECORDS.records=0 DATA.log_folder={log_folder}',
#     f'python /home/ann/Code/OutcomePrediction/Classification.py --set RUN.cv_fold=8 RUN.max_epochs=700 RUN.train_fraction=0.75 MODEL.learning_rate=2.5e-3 MODEL.dropout_prob=0.5 DATA.model_name="DSize0.75" MODEL.optimizer="Adam" MODEL.opt_params=dict() DATA.clinical_cols="{clinical_cols}" DATA.categorical_cols="{categorical_cols}" DATA.patient_ids_file_path="SubjectList.csv" RECORDS.records=0 DATA.log_folder={log_folder}',
#     f'python /home/ann/Code/OutcomePrediction/Classification.py --set RUN.cv_fold=9 RUN.max_epochs=700 RUN.train_fraction=0.75 MODEL.learning_rate=2.5e-3 MODEL.dropout_prob=0.5 DATA.model_name="DSize0.75" MODEL.optimizer="Adam" MODEL.opt_params=dict() DATA.clinical_cols="{clinical_cols}" DATA.categorical_cols="{categorical_cols}" DATA.patient_ids_file_path="SubjectList.csv" RECORDS.records=0 DATA.log_folder={log_folder}',
# ]

steps = [
    f'python /home/ann/Code/OutcomePrediction/Classification.py --set RUN.cv_fold=0 RUN.max_epochs=500 RUN.train_fraction=1.0 MODEL.learning_rate=2.0e-3 MODEL.dropout_prob=0.5 DATA.model_name="DSize1.0" MODEL.optimizer="Adam" MODEL.opt_params=dict() DATA.clinical_cols="{clinical_cols}" DATA.categorical_cols="{categorical_cols}" DATA.patient_ids_file_path="SubjectList.csv" RECORDS.records=0 DATA.log_folder={log_folder}',
    # f'python /home/ann/Code/OutcomePrediction/Classification.py --set RUN.cv_fold=1 RUN.max_epochs=500 RUN.train_fraction=0.5 MODEL.learning_rate=2.0e-3 MODEL.dropout_prob=0.5 DATA.model_name="DSize0.5" MODEL.optimizer="Adam" MODEL.opt_params=dict() DATA.clinical_cols="{clinical_cols}" DATA.categorical_cols="{categorical_cols}" DATA.patient_ids_file_path="SubjectList.csv" RECORDS.records=0 DATA.log_folder={log_folder}',
    # f'python /home/ann/Code/OutcomePrediction/Classification.py --set RUN.cv_fold=2 RUN.max_epochs=500 RUN.train_fraction=0.5 MODEL.learning_rate=2.0e-3 MODEL.dropout_prob=0.5 DATA.model_name="DSize0.5" MODEL.optimizer="Adam" MODEL.opt_params=dict() DATA.clinical_cols="{clinical_cols}" DATA.categorical_cols="{categorical_cols}" DATA.patient_ids_file_path="SubjectList.csv" RECORDS.records=0 DATA.log_folder={log_folder}',
    # f'python /home/ann/Code/OutcomePrediction/Classification.py --set RUN.cv_fold=3 RUN.max_epochs=500 RUN.train_fraction=0.5 MODEL.learning_rate=2.0e-3 MODEL.dropout_prob=0.5 DATA.model_name="DSize0.5" MODEL.optimizer="Adam" MODEL.opt_params=dict() DATA.clinical_cols="{clinical_cols}" DATA.categorical_cols="{categorical_cols}" DATA.patient_ids_file_path="SubjectList.csv" RECORDS.records=0 DATA.log_folder={log_folder}',
    # f'python /home/ann/Code/OutcomePrediction/Classification.py --set RUN.cv_fold=4 RUN.max_epochs=500 RUN.train_fraction=0.5 MODEL.learning_rate=2.0e-3 MODEL.dropout_prob=0.5 DATA.model_name="DSize0.5" MODEL.optimizer="Adam" MODEL.opt_params=dict() DATA.clinical_cols="{clinical_cols}" DATA.categorical_cols="{categorical_cols}" DATA.patient_ids_file_path="SubjectList.csv" RECORDS.records=0 DATA.log_folder={log_folder}',
    # f'python /home/ann/Code/OutcomePrediction/Classification.py --set RUN.cv_fold=5 RUN.max_epochs=500 RUN.train_fraction=0.5 MODEL.learning_rate=2.0e-3 MODEL.dropout_prob=0.5 DATA.model_name="DSize0.5" MODEL.optimizer="Adam" MODEL.opt_params=dict() DATA.clinical_cols="{clinical_cols}" DATA.categorical_cols="{categorical_cols}" DATA.patient_ids_file_path="SubjectList.csv" RECORDS.records=0 DATA.log_folder={log_folder}',
    # f'python /home/ann/Code/OutcomePrediction/Classification.py --set RUN.cv_fold=6 RUN.max_epochs=500 RUN.train_fraction=0.5 MODEL.learning_rate=2.0e-3 MODEL.dropout_prob=0.5 DATA.model_name="DSize0.5" MODEL.optimizer="Adam" MODEL.opt_params=dict() DATA.clinical_cols="{clinical_cols}" DATA.categorical_cols="{categorical_cols}" DATA.patient_ids_file_path="SubjectList.csv" RECORDS.records=0 DATA.log_folder={log_folder}',
    # f'python /home/ann/Code/OutcomePrediction/Classification.py --set RUN.cv_fold=7 RUN.max_epochs=500 RUN.train_fraction=0.5 MODEL.learning_rate=2.0e-3 MODEL.dropout_prob=0.5 DATA.model_name="DSize0.5" MODEL.optimizer="Adam" MODEL.opt_params=dict() DATA.clinical_cols="{clinical_cols}" DATA.categorical_cols="{categorical_cols}" DATA.patient_ids_file_path="SubjectList.csv" RECORDS.records=0 DATA.log_folder={log_folder}',
    # f'python /home/ann/Code/OutcomePrediction/Classification.py --set RUN.cv_fold=8 RUN.max_epochs=500 RUN.train_fraction=0.5 MODEL.learning_rate=2.0e-3 MODEL.dropout_prob=0.5 DATA.model_name="DSize0.5" MODEL.optimizer="Adam" MODEL.opt_params=dict() DATA.clinical_cols="{clinical_cols}" DATA.categorical_cols="{categorical_cols}" DATA.patient_ids_file_path="SubjectList.csv" RECORDS.records=0 DATA.log_folder={log_folder}',
    # f'python /home/ann/Code/OutcomePrediction/Classification.py --set RUN.cv_fold=9 RUN.max_epochs=500 RUN.train_fraction=0.5 MODEL.learning_rate=2.0e-3 MODEL.dropout_prob=0.5 DATA.model_name="DSize0.5" MODEL.optimizer="Adam" MODEL.opt_params=dict() DATA.clinical_cols="{clinical_cols}" DATA.categorical_cols="{categorical_cols}" DATA.patient_ids_file_path="SubjectList.csv" RECORDS.records=0 DATA.log_folder={log_folder}',
    # f'python /home/ann/Code/OutcomePrediction/Classification.py --set RUN.cv_fold=0 RUN.max_epochs=700 RUN.train_fraction=0.50 MODEL.learning_rate=2.5e-3 MODEL.dropout_prob=0.5 DATA.model_name="AdamResD0.5" MODEL.optimizer="Adam" MODEL.opt_params=dict() DATA.clinical_cols="{clinical_cols}" DATA.categorical_cols="{categorical_cols}" DATA.patient_ids_file_path="SubjectList.csv" RECORDS.records=1 DATA.log_folder={log_folder}',
    # f'python /home/ann/Code/OutcomePrediction/Classification.py --set RUN.cv_fold=1 RUN.max_epochs=700 RUN.train_fraction=0.50 MODEL.learning_rate=2.5e-3 MODEL.dropout_prob=0.5 DATA.model_name="AdamResD0.5" MODEL.optimizer="Adam" MODEL.opt_params=dict() DATA.clinical_cols="{clinical_cols}" DATA.categorical_cols="{categorical_cols}" DATA.patient_ids_file_path="SubjectList.csv" RECORDS.records=1 DATA.log_folder={log_folder}',
    # f'python /home/ann/Code/OutcomePrediction/Classification.py --set RUN.cv_fold=2 RUN.max_epochs=700 RUN.train_fraction=0.50 MODEL.learning_rate=2.5e-3 MODEL.dropout_prob=0.5 DATA.model_name="AdamResD0.5" MODEL.optimizer="Adam" MODEL.opt_params=dict() DATA.clinical_cols="{clinical_cols}" DATA.categorical_cols="{categorical_cols}" DATA.patient_ids_file_path="SubjectList.csv" RECORDS.records=1 DATA.log_folder={log_folder}',
    # f'python /home/ann/Code/OutcomePrediction/Classification.py --set RUN.cv_fold=3 RUN.max_epochs=700 RUN.train_fraction=0.50 MODEL.learning_rate=2.5e-3 MODEL.dropout_prob=0.5 DATA.model_name="AdamResD0.5" MODEL.optimizer="Adam" MODEL.opt_params=dict() DATA.clinical_cols="{clinical_cols}" DATA.categorical_cols="{categorical_cols}" DATA.patient_ids_file_path="SubjectList.csv" RECORDS.records=1 DATA.log_folder={log_folder}',
    # f'python /home/ann/Code/OutcomePrediction/Classification.py --set RUN.cv_fold=4 RUN.max_epochs=700 RUN.train_fraction=0.50 MODEL.learning_rate=2.5e-3 MODEL.dropout_prob=0.5 DATA.model_name="AdamResD0.5" MODEL.optimizer="Adam" MODEL.opt_params=dict() DATA.clinical_cols="{clinical_cols}" DATA.categorical_cols="{categorical_cols}" DATA.patient_ids_file_path="SubjectList.csv" RECORDS.records=1 DATA.log_folder={log_folder}',
    # f'python /home/ann/Code/OutcomePrediction/Classification.py --set RUN.cv_fold=5 RUN.max_epochs=700 RUN.train_fraction=0.50 MODEL.learning_rate=2.5e-3 MODEL.dropout_prob=0.5 DATA.model_name="AdamResD0.5" MODEL.optimizer="Adam" MODEL.opt_params=dict() DATA.clinical_cols="{clinical_cols}" DATA.categorical_cols="{categorical_cols}" DATA.patient_ids_file_path="SubjectList.csv" RECORDS.records=1 DATA.log_folder={log_folder}',
    # f'python /home/ann/Code/OutcomePrediction/Classification.py --set RUN.cv_fold=6 RUN.max_epochs=700 RUN.train_fraction=0.50 MODEL.learning_rate=2.5e-3 MODEL.dropout_prob=0.5 DATA.model_name="AdamResD0.5" MODEL.optimizer="Adam" MODEL.opt_params=dict() DATA.clinical_cols="{clinical_cols}" DATA.categorical_cols="{categorical_cols}" DATA.patient_ids_file_path="SubjectList.csv" RECORDS.records=1 DATA.log_folder={log_folder}',
    # f'python /home/ann/Code/OutcomePrediction/Classification.py --set RUN.cv_fold=7 RUN.max_epochs=700 RUN.train_fraction=0.50 MODEL.learning_rate=2.5e-3 MODEL.dropout_prob=0.5 DATA.model_name="AdamResD0.5" MODEL.optimizer="Adam" MODEL.opt_params=dict() DATA.clinical_cols="{clinical_cols}" DATA.categorical_cols="{categorical_cols}" DATA.patient_ids_file_path="SubjectList.csv" RECORDS.records=1 DATA.log_folder={log_folder}',
    # f'python /home/ann/Code/OutcomePrediction/Classification.py --set RUN.cv_fold=8 RUN.max_epochs=700 RUN.train_fraction=0.50 MODEL.learning_rate=2.5e-3 MODEL.dropout_prob=0.5 DATA.model_name="AdamResD0.5" MODEL.optimizer="Adam" MODEL.opt_params=dict() DATA.clinical_cols="{clinical_cols}" DATA.categorical_cols="{categorical_cols}" DATA.patient_ids_file_path="SubjectList.csv" RECORDS.records=1 DATA.log_folder={log_folder}',
    # f'python /home/ann/Code/OutcomePrediction/Classification.py --set RUN.cv_fold=9 RUN.max_epochs=700 RUN.train_fraction=0.50 MODEL.learning_rate=2.5e-3 MODEL.dropout_prob=0.5 DATA.model_name="AdamResD0.5" MODEL.optimizer="Adam" MODEL.opt_params=dict() DATA.clinical_cols="{clinical_cols}" DATA.categorical_cols="{categorical_cols}" DATA.patient_ids_file_path="SubjectList.csv" RECORDS.records=1 DATA.log_folder={log_folder}',
]

try:
    for s in steps:
        run(s)
    print("All steps completed.")
except subprocess.CalledProcessError as e:
    print(f"Step failed with exit code {e.returncode}: {e.cmd}", file=sys.stderr)
    sys.exit(e.returncode)
